services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  web:

    build:
      context: ./tdirnx/.
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    volumes:
    - ./tdirnx/.:/wrking
    stop_signal: SIGINT
    ports:
      - '8001:5000'
    depends_on:
      - redis
  web2:
    build:
      context: ./tdirnx2/.
      
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8002:5000'
    depends_on:
      - redis